# Generated by Django 6.0.7 on 2026-08-03 02:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('account_type', models.CharField(choices=[('CHECKING', 'Checking'), ('SAVINGS', 'Savings'), ('OTHER', 'Other')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('flow_type', models.CharField(choices=[('INFLOW', 'Inflow'), ('OUTFLOW', 'Outflow'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CashFlowMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
            ],
            options={
                'ordering': ('year', 'month'),
                'constraints': [models.UniqueConstraint(fields=('year', 'month'), name='unique_year_month')],
            },
        ),
        migrations.CreateModel(
            name='RecurringCashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('default_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frequency', models.CharField(choices=[('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Every two weeks'), ('MONTHLY', 'Monthly')], max_length=20)),
                ('anchor_date', models.DateField(blank=True, null=True)),
                ('preferred_due_day', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_cash_flows', to='ledger.account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_cash_flows', to='ledger.category')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CashFlowEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('planned_date', models.DateField()),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('PAID', 'Paid'), ('CLEARED', 'Cleared'), ('CANCELED', 'Canceled')], default='PLANNED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_flow_events', to='ledger.account')),
                ('cash_flow_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_flow_events', to='ledger.cashflowmonth')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_flow_events', to='ledger.category')),
                ('recurring_cash_flow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_flow_events', to='ledger.recurringcashflow')),
            ],
            options={
                'ordering': ('planned_date', 'created_at'),
            },
        ),
    ]
